name: flutter_app
description: Health monitoring and anomaly detection app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  http: ^1.2.1
  web_socket_channel: ^3.0.0

  # Charts
  fl_chart: ^0.68.0

  # Camera
  camera: ^0.11.0

  # Permissions
  permission_handler: ^11.3.1

  # Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
